export const SET_ERRORS = 'SET_ERRORS';
export const SET_USER = 'SET_USER';

export const SAVE_REPORT = 'SAVE_REPORT';
export const CLEAR_REPORT = 'CLEAR_REPORT';
export const SAVE_MANY_REPORTS = 'SAVE_MANY_REPORTS';
export const DELETE_REPORT = 'DELETE_REPORT';
export const LOAD_REPORT_TO_STATE = 'LOAD_REPORT_TO_STATE';